=== 17ec084/systemizing_knowledge/オブジェクト指向知識体系/class_diagram.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="systems">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element name="system">
			<xsd:complexType>
				<xsd:sequence>
					<xsd:group ref="class"/>
				</xsd:sequence>
				<xsd:attribute name="name" type="xsd:string" use="required"/>
			</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
    </xsd:element>

	<xsd:group name="class"> <!-- 再帰呼び出しにより、任意世代に対応 -->
		<xsd:sequence>
			<xsd:element name="class" minOccurs="0" maxOccurs="unbounded">
			<xsd:complexType>
				<xsd:sequence>
					<xsd:group ref="class"/>
				</xsd:sequence>
				<xsd:attribute name="name" type="xsd:string" use="required"/><!--
				<xsd:attribute name="degree" type="xsd:nonNegativeInteger" use="option"/>
				<xsd:attribute name="last_id" type="xsd:nonNegativeInteger" use="option"/> -->
			</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:group>

</xsd:schema>

=== 17ec084/systemizing_knowledge/オブジェクト指向知識体系/class_diagram.xml
<?xml version="1.0" encoding="UTF-8"?>
<systems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="class_diagram.xsd">
	<system name="テスト体系">
		<class name="自">
			<class name="親">
			</class>
			<class name="親2">
				<class name="祖父母">
					<class name="曾祖父母">
					</class>
					<class name="曾祖父母2">
					</class>
				</class>
			</class>
		</class>
		<class name="自2">
		</class>
	</system>
</systems>
